In [ ]:
## Importing packages

import pandas as pd
import numpy as np
import itertools

import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.tsa.arima.model import ARIMA

In [ ]:
## Reading data
dataRaw = pd.read_csv('./prices250.txt', delimiter = '\s+', header = None).T

## Adding column names (for each timepoint)
dataRaw.columns = ['price' + str(x) for x in range(1, dataRaw.shape[1]+1, 1)]

## Adding column representing which instrument
dataRaw['instrument'] = ['instrument' + str(x) for x in range(1, dataRaw.shape[0]+1, 1)]

## Converting to long format
data = pd.wide_to_long(dataRaw, stubnames = 'price', i = 'instrument', j = 'time')
data['instrument'] = [x[0] for x in data.index]
data['time'] = [x[1] for x in data.index]
data.reset_index(drop = True, inplace = True)

In [ ]:
## Autocorrelation graph

for i in range(1, 101, 1):
    instrument = data[data['instrument'] == ('instrument' + str(i))]['price']
    pd.plotting.autocorrelation_plot(instrument, linewidth = 0.5)

## Instrument 1 ARIMA

In [ ]:
## Subset for testing

dataInstrument1 = data[data["instrument"] == "instrument1"][["price", "time"]].set_index("time")
dataInstrument1.index = pd.to_datetime(dataInstrument1.index, unit = 'd')

In [ ]:
## Looking for optimal ARIMA parameters

# trainData = dataInstrument1["price"][:225]
# testData = dataInstrument1["price"][225:]

# p = range(30, 31, 1)
# d = q = range(0, 2)
# pdq = list(itertools.product(p, d, q))
# modelAIC = []

# for paramlist in pdq:
#     arimaModel = ARIMA(trainData, order = paramlist)
#     arimaModelFit = arimaModel.fit()
#     modelAIC.append(arimaModelFit.aic)

# for i in range(len(modelAIC)):
#     if list(modelAIC == min(modelAIC))[i] == True:
#         print(pdq[i])

In [ ]:
## Training using optimised parameters

trainData = dataInstrument1["price"][:225]
testData = dataInstrument1["price"][225:]
arimaModel = ARIMA(trainData, order = (30, 1, 0))
arimaModelFit = arimaModel.fit()
predictions = arimaModelFit.forecast(steps = 25)

testData.plot()
predictions.plot(color = "red")

In [437]:
def shortTermTrading(instrumentData, params, window, prevPosition):
    
    # Fitting ARIMA and predicting specified number of days
    arimaModel = ARIMA(instrumentData, order = params)
    arimaModelFit = arimaModel.fit()
    predictions = arimaModelFit.forecast(steps = window)

    # Only looking at observations within specified window
    instrumentDataWindow = instrumentData.iloc[0:window, :]
    
    # Obtaining prices and days within window with minimum and maximum days
    priceMin = [x == min(predictions) for x in predictions]
    priceMax = [x == max(predictions) for x in predictions]
    days = [x for x in range(0, window, 1)]
    dayMin = list(itertools.compress(days, priceMin))[0]
    dayMax = list(itertools.compress(days, priceMax))[0]

    # Obtaining lists of minimum and maximum days, prices, and non-minimum or maximum days
    minMaxDays = [dayMin, dayMax]
    minMaxPrice = list(instrumentDataWindow.iloc[minMaxDays, 0])
    otherDays = np.setdiff1d(days, minMaxDays)

    # Obtaining position
    position = np.full(shape = (window, 1), fill_value = prevPosition[-1]) # initial position all 0
    position[minMaxDays[0]] = -5000/minMaxPrice[0]
    position[minMaxDays[1]] = 5000/minMaxPrice[1]
    for i in otherDays: # all other days reflect previous day's position
        try:
            position[i] = position[i-1]
        except:
            pass

    return position

In [440]:
shortTermTrading(instrumentData = dataInstrument1, params = (30, 1, 0), window = 10, prevPosition = [0])

/Users/alanburzevski/Documents/Uni/casecomp/rho_algothon/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:524: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  warnings.warn('No frequency information was'
/Users/alanburzevski/Documents/Uni/casecomp/rho_algothon/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:524: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  warnings.warn('No frequency information was'
/Users/alanburzevski/Documents/Uni/casecomp/rho_algothon/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:524: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  warnings.warn('No frequency information was'


array([[   0],
       [ 274],
       [ 274],
       [ 274],
       [ 274],
       [ 274],
       [ 274],
       [-271],
       [-271],
       [-271]])

In [401]:
position = np.zeros(shape = (1,1))
i = 1
while i < 5:
    
    newPosition = shortTermTrading(instrumentData = dataInstrument1, params = (30, 1, 0), days = 10, prevPosition = position)
    position = np.concatenate((position, newPosition), axis=0)

    i = i+1

position

/Users/alanburzevski/Documents/Uni/casecomp/rho_algothon/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:524: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  warnings.warn('No frequency information was'
/Users/alanburzevski/Documents/Uni/casecomp/rho_algothon/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:524: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  warnings.warn('No frequency information was'
/Users/alanburzevski/Documents/Uni/casecomp/rho_algothon/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:524: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  warnings.warn('No frequency information was'
/Users/alanburzevski/Documents/Uni/casecomp/rho_algothon/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:524: ValueWarning: No frequency information was provided, so inferred frequ

array([[   0.        ],
       [   0.        ],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [-271.88689505],
       [-271.88689505],
       [-271.88689505],
       [-271.88689505],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [-271.88689505],
       [-271.88689505],
       [-271.88689505],
       [-271.88689505],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [-271.88689505],
       [-271.88689505],
       [-271.88689505],
       [-271.88689505],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [ 274.42371021],
       [-271.88689505],
       [-271.88689505],
       [-271.88689505]])

In [ ]:
position = np.zeros(shape = (10, 1))
minmax_price = shortTermTrading(instrumentData = dataInstrument1, params = (30, 1, 0), days = 10)
position[minmax_price[0][0]] = -5000/minmax_price[1][0]
position[minmax_price[0][1]] = 5000/minmax_price[1][1]

for i in minmax_price[2]:
    position[i] = position[i-1]

position

## Modern Portfolio Theory Implementation

In [ ]:
# global constants / variables
nDays = 250
nInst = 100

In [ ]:
# Reads in first 250 days' data into numpy array givenPrices
# Input: N/A
# Output: matrix of price history from training data
def readTraining ():
    f = open("prices250.txt", "r")
    givenPrices = []
    for line in f:
        row = [float(num) for num in line.split()]
        givenPrices.append(row)
    givenPrices = np.array(givenPrices)
    # print(givenPrices.shape)
    return givenPrices

# Given the price history, output daily percentage price change matrix
# Input: givenPrices (price history)
# Output: matrix of daily percentage change; dailyReturns[i-1][j-1] = percentage change of instrument j between days i and i-1
def dailyReturns (givenPrices):
    logChange = []
    # loop through each instrument
    for inst in givenPrices.T:
        logChangeInst = np.empty((nDays, 1))
        # logChangeInst = np.zeros(nDays)
        for day in range(0, nDays - 1):
            logChangeInst[day] = np.log(inst[day + 1] / inst[day])
        logChange.append(logChangeInst)
    logChange = np.array(logChange)
    # print(logChange.T.shape)
    return logChange.T

# Given the daily price changes, output the avg. daily return, SD, variance for each instrument
def returnMeasures (dailyReturns):
    measures = np.empty((3, nInst))
    measures[0] = [np.average(inst) for inst in dailyReturns.T]
    measures[1] = [np.std(inst, ddof=1) for inst in dailyReturns.T]
    measures[2] = [np.var(inst, ddof=1) for inst in dailyReturns.T]
    return measures

# Given the price history, output the excess returns matrix
# Input: givenPrices (price history)
# Output: matrix of excess returns; excessReturns[i-1][j-1] = excess returns of instrument j on day i
def excessReturns (givenPrices):
    excessReturns = []
    # get the required matrices for further computation
    Returns = dailyReturns(givenPrices)
    measures = returnMeasures(Returns)

    for inst in range(nInst):
        instExcess = np.empty(nDays - 1) 
        instReturns = (Returns.T)[inst]
        for i in range (0, nDays - 1):
            instExcess[i] = instReturns[i] - measures[0][inst]
        excessReturns.append(instExcess)

    excessReturns = np.array(excessReturns)
    print(excessReturns.T.shape)
    return excessReturns.T

# Calculate the variance covariance matrix
# Input: excess returns
# Output: variance covariance matrix
def varCov (givenExcess):
    varCovMat = np.matmul(givenExcess.T, givenExcess)/(249 - 1) # -1 because sample std
    return varCovMat

# Calculate the scaled variance covariance matrix
# Input: variance covariance matrix
# Output: scaled variance covariance matrix
def sigma (varCovMat):
    sigmaMat = varCovMat*250
    return sigmaMat

# Calculate weights
# Input: average returns, inverse scaled variance covariance matrix, and target returns
# Output: weights for optimal portfolio given target returns
def getWeights(returns, inverseSigma, targetReturn):
    ones = np.ones(nInst)
    A = np.matmul(np.matmul(ones, inverseSigma), ones.T)
    B = np.matmul(np.matmul(ones, inverseSigma), returns.T)
    C = np.matmul(np.matmul(returns, inverseSigma), returns.T)
    delta = A * C - B**2
    lam = (C - targetReturn*B)/delta
    gam = (targetReturn*A - B)/delta

    weightsTerm1 = lam * np.matmul(inverseSigma, ones.T)
    weightsTerm2 = gam * np.matmul(inverseSigma, returns.T)
    weights = weightsTerm1 + weightsTerm2
    return(weights)  

In [ ]:
## Test to get weights

returns = returnMeasures(dailyReturns(readTraining()))[0]*250
inverseSigma = np.linalg.inv(sigma(varCov(excessReturns(readTraining()))))
targetReturn = 0.05
getWeights(returns, sigma, targetReturn)  

In [423]:
def minmaxTransform(OldValue, NewMin, NewMax):
    OldMax = max(OldValue)
    OldMin = min(OldValue)

    newValue = np.zeros(len(OldValue))
    for index, value in enumerate(OldValue):
        newValue[index] = (((value - OldMin) * (NewMax - NewMin)) / (OldMax - OldMin)) + NewMin

    return newValue

weights = [2.38, 7.05, 8.17, -1.74, -7.50, 0.35, -5.19, 1.05, 12.90, -4.33, 14.58, 0.44, 4.44, -3.56, -1.65, 1.77, 4.74, 2.55, -0.34, 1.28, -2.30, 9.38, 5.00, -0.43, 0.95, -0.35, 31.78, 1.46, 2.11, 1.01, 6.33, 0.72, 3.92, 4.52, 0.40, -0.70, -2.75, -0.31, 9.68, 0.88, 1.45, 5.64, -12.95, 2.79, 3.45, 3.32, -4.98, -3.14, 2.48, -4.63, 0.19, 0.36, 0.21, -0.21, -0.39, -0.24, -0.40, -0.71, 1.07, 0.17, -0.25, -0.38, -0.66, 0.34, -0.02, 0.44, -0.48, -0.27, 0.09, 0.13, 0.08, 0.35, 0.13, -0.24, -0.13, 0.09, -0.21, -0.44, -0.05, -0.09, -0.48, -0.32, -0.11, -0.25, 0.06, -0.38, -0.11, 0.68, -0.77, 0.73, -0.50, 0.55, 0.12, 0.27, -0.54, -0.17, 0.51, 0.56, -0.19, -0.28]

transformWeights = minmaxTransform(weights, -1, 1)
longHoldings = transformWeights

longHoldings

array([-0.31455399, -0.10574558, -0.05566734, -0.4987704 , -0.75631567,
       -0.40532081, -0.65302929, -0.37402191,  0.15582383, -0.61457635,
        0.2309412 , -0.40129667, -0.22244579, -0.58014755, -0.49474626,
       -0.34182875, -0.20903197, -0.30695283, -0.43617259, -0.36373798,
       -0.52380952, -0.00156495, -0.19740666, -0.44019674, -0.37849318,
       -0.43661972,  1.        , -0.35568969, -0.32662643, -0.37581042,
       -0.13793874, -0.38877711, -0.2456964 , -0.21886877, -0.40308518,
       -0.45226917, -0.54393025, -0.43483121,  0.01184887, -0.38162307,
       -0.35613682, -0.16879052, -1.        , -0.29622178, -0.26671138,
       -0.27252403, -0.64363962, -0.56136821, -0.31008272, -0.62799016,
       -0.41247485, -0.40487369, -0.41158059, -0.43035994, -0.43840823,
       -0.43170132, -0.43885535, -0.4527163 , -0.37312765, -0.4133691 ,
       -0.43214845, -0.4379611 , -0.45048066, -0.40576794, -0.42186452,
       -0.40129667, -0.44243237, -0.4330427 , -0.41694612, -0.41